### ISSUE TITLE
Demo full screen widget per calendar

### ISSUE THREAD

**Issue by saumier** [culturecreates/artsdata-widget#1]
Please add the user story and solution in the [widget doc](https://docs.google.com/document/d/1I7sKHZEYNgOd2FJgDhTXysqNmA4K2f3fUHL9OZDfWlI/edit)

**Comment by SyamBabu-M** [comment]
@saumier I have added the user story and implementation logic in the [doc](https://docs.google.com/document/d/1I7sKHZEYNgOd2FJgDhTXysqNmA4K2f3fUHL9OZDfWlI/edit#heading=h.j1meoh9u8yaj). Please review it and let me know what you think.
